batch_size: 8
beta1: 0.9
beta2: 0.999
dataset_name:
  - RDD
  - Jung
  - Kliger
height: 256
lambda1: 1.0
lambda2: 0.01
learning_rate: 0.00039
loss_function_name: GAN
max_epoch: 400
model: ViTBGShadowNet
vit_pretrained: True
num_workers: 4
pretrained: True
width: 256
