batch_size: 4
beta1: 0.9
beta2: 0.999
dataset_name: RDD
height: 256
lambda1: 1.0
lambda2: 0.01
learning_rate: 0.00039
loss_function_name: L1
max_epoch: 400
model: ViTCBENet
vit_pretrained: True
num_workers: 4
pretrained: True
width: 256
